/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_config_5finstance_2eproto__INCLUDED
#define PROTOBUF_C_config_5finstance_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _CFGINSTANCE CFGINSTANCE;
typedef struct _CFGINSTANCES CFGINSTANCES;


/* --- enums --- */


/* --- messages --- */

struct  _CFGINSTANCE
{
  ProtobufCMessage base;
  int32_t id;
  char *name;
  int32_t res_id;
  size_t n_dropthing_id;
  int32_t *dropthing_id;
};
#define CFG__INSTANCE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cfg__instance__descriptor) \
    , 0, NULL, 0, 0,NULL }


struct  _CFGINSTANCES
{
  ProtobufCMessage base;
  size_t n_instance;
  CFGINSTANCE **instance;
};
#define CFG__INSTANCES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cfg__instances__descriptor) \
    , 0,NULL }


/* CFGINSTANCE methods */
void   cfg__instance__init
                     (CFGINSTANCE         *message);
size_t cfg__instance__get_packed_size
                     (const CFGINSTANCE   *message);
size_t cfg__instance__pack
                     (const CFGINSTANCE   *message,
                      uint8_t             *out);
size_t cfg__instance__pack_to_buffer
                     (const CFGINSTANCE   *message,
                      ProtobufCBuffer     *buffer);
CFGINSTANCE *
       cfg__instance__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cfg__instance__free_unpacked
                     (CFGINSTANCE *message,
                      ProtobufCAllocator *allocator);
/* CFGINSTANCES methods */
void   cfg__instances__init
                     (CFGINSTANCES         *message);
size_t cfg__instances__get_packed_size
                     (const CFGINSTANCES   *message);
size_t cfg__instances__pack
                     (const CFGINSTANCES   *message,
                      uint8_t             *out);
size_t cfg__instances__pack_to_buffer
                     (const CFGINSTANCES   *message,
                      ProtobufCBuffer     *buffer);
CFGINSTANCES *
       cfg__instances__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cfg__instances__free_unpacked
                     (CFGINSTANCES *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CFGINSTANCE_Closure)
                 (const CFGINSTANCE *message,
                  void *closure_data);
typedef void (*CFGINSTANCES_Closure)
                 (const CFGINSTANCES *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor cfg__instance__descriptor;
extern const ProtobufCMessageDescriptor cfg__instances__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_config_5finstance_2eproto__INCLUDED */
