/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "config_pinstance.pb-c.h"
void   config__pinstance__init
                     (CONFIGPINSTANCE         *message)
{
  static CONFIGPINSTANCE init_value = CONFIG__PINSTANCE__INIT;
  *message = init_value;
}
size_t config__pinstance__get_packed_size
                     (const CONFIGPINSTANCE *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &config__pinstance__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t config__pinstance__pack
                     (const CONFIGPINSTANCE *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &config__pinstance__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t config__pinstance__pack_to_buffer
                     (const CONFIGPINSTANCE *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &config__pinstance__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CONFIGPINSTANCE *
       config__pinstance__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CONFIGPINSTANCE *)
     protobuf_c_message_unpack (&config__pinstance__descriptor,
                                allocator, len, data);
}
void   config__pinstance__free_unpacked
                     (CONFIGPINSTANCE *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &config__pinstance__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   config__pinstances__init
                     (CONFIGPINSTANCES         *message)
{
  static CONFIGPINSTANCES init_value = CONFIG__PINSTANCES__INIT;
  *message = init_value;
}
size_t config__pinstances__get_packed_size
                     (const CONFIGPINSTANCES *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &config__pinstances__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t config__pinstances__pack
                     (const CONFIGPINSTANCES *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &config__pinstances__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t config__pinstances__pack_to_buffer
                     (const CONFIGPINSTANCES *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &config__pinstances__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CONFIGPINSTANCES *
       config__pinstances__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CONFIGPINSTANCES *)
     protobuf_c_message_unpack (&config__pinstances__descriptor,
                                allocator, len, data);
}
void   config__pinstances__free_unpacked
                     (CONFIGPINSTANCES *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &config__pinstances__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor config__pinstance__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CONFIGPINSTANCE, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CONFIGPINSTANCE, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "res_id",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CONFIGPINSTANCE, res_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dropthing_id",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(CONFIGPINSTANCE, n_dropthing_id),
    PROTOBUF_C_OFFSETOF(CONFIGPINSTANCE, dropthing_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned config__pinstance__field_indices_by_name[] = {
  3,   /* field[3] = dropthing_id */
  0,   /* field[0] = id */
  1,   /* field[1] = name */
  2,   /* field[2] = res_id */
};
static const ProtobufCIntRange config__pinstance__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor config__pinstance__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "CONFIG_PINSTANCE",
  "CONFIGPINSTANCE",
  "CONFIGPINSTANCE",
  "",
  sizeof(CONFIGPINSTANCE),
  4,
  config__pinstance__field_descriptors,
  config__pinstance__field_indices_by_name,
  1,  config__pinstance__number_ranges,
  (ProtobufCMessageInit) config__pinstance__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor config__pinstances__field_descriptors[1] =
{
  {
    "pinstance",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(CONFIGPINSTANCES, n_pinstance),
    PROTOBUF_C_OFFSETOF(CONFIGPINSTANCES, pinstance),
    &config__pinstance__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned config__pinstances__field_indices_by_name[] = {
  0,   /* field[0] = pinstance */
};
static const ProtobufCIntRange config__pinstances__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor config__pinstances__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "CONFIG_PINSTANCES",
  "CONFIGPINSTANCES",
  "CONFIGPINSTANCES",
  "",
  sizeof(CONFIGPINSTANCES),
  1,
  config__pinstances__field_descriptors,
  config__pinstances__field_indices_by_name,
  1,  config__pinstances__number_ranges,
  (ProtobufCMessageInit) config__pinstances__init,
  NULL,NULL,NULL    /* reserved[123] */
};
