/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_config_5fitem_2eproto__INCLUDED
#define PROTOBUF_C_config_5fitem_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS




/* --- enums --- */


/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */


/* --- descriptors --- */


PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_config_5fitem_2eproto__INCLUDED */
