/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "NPC.pb-c.h"
void   npc__init
                     (NPC         *message)
{
  static NPC init_value = NPC__INIT;
  *message = init_value;
}
size_t npc__get_packed_size
                     (const NPC *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &npc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t npc__pack
                     (const NPC *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &npc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t npc__pack_to_buffer
                     (const NPC *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &npc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NPC *
       npc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NPC *)
     protobuf_c_message_unpack (&npc__descriptor,
                                allocator, len, data);
}
void   npc__free_unpacked
                     (NPC *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &npc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   npcs__init
                     (NPCS         *message)
{
  static NPCS init_value = NPCS__INIT;
  *message = init_value;
}
size_t npcs__get_packed_size
                     (const NPCS *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &npcs__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t npcs__pack
                     (const NPCS *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &npcs__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t npcs__pack_to_buffer
                     (const NPCS *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &npcs__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NPCS *
       npcs__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NPCS *)
     protobuf_c_message_unpack (&npcs__descriptor,
                                allocator, len, data);
}
void   npcs__free_unpacked
                     (NPCS *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &npcs__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor npc__field_descriptors[6] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NPC, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NPC, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scene_id",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NPC, scene_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_x",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NPC, pos_x),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_y",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NPC, pos_y),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "func",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(NPC, n_func),
    PROTOBUF_C_OFFSETOF(NPC, func),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned npc__field_indices_by_name[] = {
  5,   /* field[5] = func */
  0,   /* field[0] = id */
  1,   /* field[1] = name */
  3,   /* field[3] = pos_x */
  4,   /* field[4] = pos_y */
  2,   /* field[2] = scene_id */
};
static const ProtobufCIntRange npc__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor npc__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NPC",
  "NPC",
  "NPC",
  "",
  sizeof(NPC),
  6,
  npc__field_descriptors,
  npc__field_indices_by_name,
  1,  npc__number_ranges,
  (ProtobufCMessageInit) npc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor npcs__field_descriptors[1] =
{
  {
    "npc",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(NPCS, n_npc),
    PROTOBUF_C_OFFSETOF(NPCS, npc),
    &npc__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned npcs__field_indices_by_name[] = {
  0,   /* field[0] = npc */
};
static const ProtobufCIntRange npcs__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor npcs__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "NPCS",
  "NPCS",
  "NPCS",
  "",
  sizeof(NPCS),
  1,
  npcs__field_descriptors,
  npcs__field_indices_by_name,
  1,  npcs__number_ranges,
  (ProtobufCMessageInit) npcs__init,
  NULL,NULL,NULL    /* reserved[123] */
};
