/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "err.pb-c.h"
const ProtobufCEnumValue cs__error__no__enum_values_by_number[4] =
{
  { "ERR_SUCCESS", "CS__ERROR__NO__ERR_SUCCESS", 0 },
  { "ERR_INSTANCE_ENTERFIGHT", "CS__ERROR__NO__ERR_INSTANCE_ENTERFIGHT", 1 },
  { "ERR_LOGIN_ROLE_NOT_EXIST", "CS__ERROR__NO__ERR_LOGIN_ROLE_NOT_EXIST", 2 },
  { "ERR_CREATEROLE_NAME_EXIST", "CS__ERROR__NO__ERR_CREATEROLE_NAME_EXIST", 3 },
};
static const ProtobufCIntRange cs__error__no__value_ranges[] = {
{0, 0},{0, 4}
};
const ProtobufCEnumValueIndex cs__error__no__enum_values_by_name[4] =
{
  { "ERR_CREATEROLE_NAME_EXIST", 3 },
  { "ERR_INSTANCE_ENTERFIGHT", 1 },
  { "ERR_LOGIN_ROLE_NOT_EXIST", 2 },
  { "ERR_SUCCESS", 0 },
};
const ProtobufCEnumDescriptor cs__error__no__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "CS_ERROR_NO",
  "CS_ERROR_NO",
  "CSERRORNO",
  "",
  4,
  cs__error__no__enum_values_by_number,
  4,
  cs__error__no__enum_values_by_name,
  1,
  cs__error__no__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
