/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_err_2eproto__INCLUDED
#define PROTOBUF_C_err_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS




/* --- enums --- */

typedef enum _CSERRORNO {
  CS__ERROR__NO__ERR_SUCCESS = 0,
  CS__ERROR__NO__ERR_INSTANCE_ENTERFIGHT = 1,
  CS__ERROR__NO__ERR_LOGIN_ROLE_NOT_EXIST = 2,
  CS__ERROR__NO__ERR_CREATEROLE_NAME_EXIST = 3
} CSERRORNO;

/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    cs__error__no__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_err_2eproto__INCLUDED */
