CREATE TABLE IF NOT EXISTS DBRoleInfo (
    id INT UNSIGNED NOT NULL  DEFAULT '9999',
    name VARCHAR(64) NOT NULL  DEFAULT '',
    profession TINYINT NOT NULL  DEFAULT '1',
    level INT NOT NULL  DEFAULT '1',
    create_time DATETIME NOT NULL  DEFAULT '2010-01-01 00:00:00',
    scene_id SMALLINT UNSIGNED NOT NULL  DEFAULT '0',
    pos_x INT UNSIGNED NOT NULL  DEFAULT '0',
    pos_y INT UNSIGNED NOT NULL  DEFAULT '0',
    gold BIGINT NOT NULL  DEFAULT '0',
    attribute BLOB,
    bag BLOB,
    PRIMARY KEY(id),
    UNIQUE (name))
ENGINE=InnoDB DEFAULT CHARSET=latin1;