/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_config_5fkeyword_2eproto__INCLUDED
#define PROTOBUF_C_config_5fkeyword_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _CFGKEYWORD CFGKEYWORD;
typedef struct _CFGKEYWORDS CFGKEYWORDS;


/* --- enums --- */


/* --- messages --- */

struct  _CFGKEYWORD
{
  ProtobufCMessage base;
  char *group;
  int32_t value;
  char *desc;
};
#define CFG__KEYWORD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cfg__keyword__descriptor) \
    , NULL, 0, NULL }


struct  _CFGKEYWORDS
{
  ProtobufCMessage base;
  size_t n_keyword;
  CFGKEYWORD **keyword;
};
#define CFG__KEYWORDS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cfg__keywords__descriptor) \
    , 0,NULL }


/* CFGKEYWORD methods */
void   cfg__keyword__init
                     (CFGKEYWORD         *message);
size_t cfg__keyword__get_packed_size
                     (const CFGKEYWORD   *message);
size_t cfg__keyword__pack
                     (const CFGKEYWORD   *message,
                      uint8_t             *out);
size_t cfg__keyword__pack_to_buffer
                     (const CFGKEYWORD   *message,
                      ProtobufCBuffer     *buffer);
CFGKEYWORD *
       cfg__keyword__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cfg__keyword__free_unpacked
                     (CFGKEYWORD *message,
                      ProtobufCAllocator *allocator);
/* CFGKEYWORDS methods */
void   cfg__keywords__init
                     (CFGKEYWORDS         *message);
size_t cfg__keywords__get_packed_size
                     (const CFGKEYWORDS   *message);
size_t cfg__keywords__pack
                     (const CFGKEYWORDS   *message,
                      uint8_t             *out);
size_t cfg__keywords__pack_to_buffer
                     (const CFGKEYWORDS   *message,
                      ProtobufCBuffer     *buffer);
CFGKEYWORDS *
       cfg__keywords__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cfg__keywords__free_unpacked
                     (CFGKEYWORDS *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CFGKEYWORD_Closure)
                 (const CFGKEYWORD *message,
                  void *closure_data);
typedef void (*CFGKEYWORDS_Closure)
                 (const CFGKEYWORDS *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor cfg__keyword__descriptor;
extern const ProtobufCMessageDescriptor cfg__keywords__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_config_5fkeyword_2eproto__INCLUDED */
