/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "config_name.pb-c.h"
void   cfg__name__init
                     (CFGNAME         *message)
{
  static CFGNAME init_value = CFG__NAME__INIT;
  *message = init_value;
}
size_t cfg__name__get_packed_size
                     (const CFGNAME *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__name__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cfg__name__pack
                     (const CFGNAME *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__name__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cfg__name__pack_to_buffer
                     (const CFGNAME *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__name__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CFGNAME *
       cfg__name__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CFGNAME *)
     protobuf_c_message_unpack (&cfg__name__descriptor,
                                allocator, len, data);
}
void   cfg__name__free_unpacked
                     (CFGNAME *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__name__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor cfg__name__field_descriptors[3] =
{
  {
    "fam_name",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(CFGNAME, n_fam_name),
    PROTOBUF_C_OFFSETOF(CFGNAME, fam_name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "male_name",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(CFGNAME, n_male_name),
    PROTOBUF_C_OFFSETOF(CFGNAME, male_name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "female_name",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(CFGNAME, n_female_name),
    PROTOBUF_C_OFFSETOF(CFGNAME, female_name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cfg__name__field_indices_by_name[] = {
  0,   /* field[0] = fam_name */
  2,   /* field[2] = female_name */
  1,   /* field[1] = male_name */
};
static const ProtobufCIntRange cfg__name__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor cfg__name__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "CFG_NAME",
  "CFGNAME",
  "CFGNAME",
  "",
  sizeof(CFGNAME),
  3,
  cfg__name__field_descriptors,
  cfg__name__field_indices_by_name,
  1,  cfg__name__number_ranges,
  (ProtobufCMessageInit) cfg__name__init,
  NULL,NULL,NULL    /* reserved[123] */
};
