/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_config_5fquest_5fmain_2eproto__INCLUDED
#define PROTOBUF_C_config_5fquest_5fmain_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _CFGMAINQUEST CFGMAINQUEST;
typedef struct _CFGMAINQUESTS CFGMAINQUESTS;


/* --- enums --- */


/* --- messages --- */

struct  _CFGMAINQUEST
{
  ProtobufCMessage base;
  int32_t id;
  char *name;
  int32_t type;
  int32_t npc;
  int32_t level;
  char *msg1;
  char *button1;
  char *msg2;
  char *button2;
  char *msg3;
  char *button3;
  char *msg4;
  char *button4;
  char *desc;
  int32_t map;
  int32_t finish_npc;
  int32_t finish_level;
  int32_t kill_npc;
  int32_t collect_item;
  int32_t award_item1;
  int32_t award_item1_num;
  int32_t award_item2;
  int32_t award_item2_num;
  int32_t award_exp;
  int32_t award_money;
  int32_t award_friendly;
  int32_t script;
  int32_t animation;
  int32_t trig_msg;
  char *cond_msg1;
  char *cond_button1;
  char *cond_msg2;
  char *cond_button2;
  char *cond_msg3;
  char *cond_button3;
  char *finish_msg1;
  char *finish_button1;
  char *finish_msg2;
  char *finish_button2;
  char *finish_msg3;
  char *finish_button3;
  char *inprog_msg;
  char *inprog_button;
};
#define CFG__MAIN__QUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cfg__main__quest__descriptor) \
    , 0, NULL, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }


struct  _CFGMAINQUESTS
{
  ProtobufCMessage base;
  size_t n_quest;
  CFGMAINQUEST **quest;
};
#define CFG__MAIN__QUESTS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cfg__main__quests__descriptor) \
    , 0,NULL }


/* CFGMAINQUEST methods */
void   cfg__main__quest__init
                     (CFGMAINQUEST         *message);
size_t cfg__main__quest__get_packed_size
                     (const CFGMAINQUEST   *message);
size_t cfg__main__quest__pack
                     (const CFGMAINQUEST   *message,
                      uint8_t             *out);
size_t cfg__main__quest__pack_to_buffer
                     (const CFGMAINQUEST   *message,
                      ProtobufCBuffer     *buffer);
CFGMAINQUEST *
       cfg__main__quest__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cfg__main__quest__free_unpacked
                     (CFGMAINQUEST *message,
                      ProtobufCAllocator *allocator);
/* CFGMAINQUESTS methods */
void   cfg__main__quests__init
                     (CFGMAINQUESTS         *message);
size_t cfg__main__quests__get_packed_size
                     (const CFGMAINQUESTS   *message);
size_t cfg__main__quests__pack
                     (const CFGMAINQUESTS   *message,
                      uint8_t             *out);
size_t cfg__main__quests__pack_to_buffer
                     (const CFGMAINQUESTS   *message,
                      ProtobufCBuffer     *buffer);
CFGMAINQUESTS *
       cfg__main__quests__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cfg__main__quests__free_unpacked
                     (CFGMAINQUESTS *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CFGMAINQUEST_Closure)
                 (const CFGMAINQUEST *message,
                  void *closure_data);
typedef void (*CFGMAINQUESTS_Closure)
                 (const CFGMAINQUESTS *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor cfg__main__quest__descriptor;
extern const ProtobufCMessageDescriptor cfg__main__quests__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_config_5fquest_5fmain_2eproto__INCLUDED */
