/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "config_instance.pb-c.h"
void   cfg__instance__init
                     (CFGINSTANCE         *message)
{
  static CFGINSTANCE init_value = CFG__INSTANCE__INIT;
  *message = init_value;
}
size_t cfg__instance__get_packed_size
                     (const CFGINSTANCE *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__instance__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cfg__instance__pack
                     (const CFGINSTANCE *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__instance__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cfg__instance__pack_to_buffer
                     (const CFGINSTANCE *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__instance__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CFGINSTANCE *
       cfg__instance__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CFGINSTANCE *)
     protobuf_c_message_unpack (&cfg__instance__descriptor,
                                allocator, len, data);
}
void   cfg__instance__free_unpacked
                     (CFGINSTANCE *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__instance__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cfg__instances__init
                     (CFGINSTANCES         *message)
{
  static CFGINSTANCES init_value = CFG__INSTANCES__INIT;
  *message = init_value;
}
size_t cfg__instances__get_packed_size
                     (const CFGINSTANCES *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__instances__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cfg__instances__pack
                     (const CFGINSTANCES *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__instances__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cfg__instances__pack_to_buffer
                     (const CFGINSTANCES *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__instances__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CFGINSTANCES *
       cfg__instances__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CFGINSTANCES *)
     protobuf_c_message_unpack (&cfg__instances__descriptor,
                                allocator, len, data);
}
void   cfg__instances__free_unpacked
                     (CFGINSTANCES *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__instances__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor cfg__instance__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGINSTANCE, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGINSTANCE, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "res_id",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGINSTANCE, res_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dropthing_id",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(CFGINSTANCE, n_dropthing_id),
    PROTOBUF_C_OFFSETOF(CFGINSTANCE, dropthing_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cfg__instance__field_indices_by_name[] = {
  3,   /* field[3] = dropthing_id */
  0,   /* field[0] = id */
  1,   /* field[1] = name */
  2,   /* field[2] = res_id */
};
static const ProtobufCIntRange cfg__instance__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor cfg__instance__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "CFG_INSTANCE",
  "CFGINSTANCE",
  "CFGINSTANCE",
  "",
  sizeof(CFGINSTANCE),
  4,
  cfg__instance__field_descriptors,
  cfg__instance__field_indices_by_name,
  1,  cfg__instance__number_ranges,
  (ProtobufCMessageInit) cfg__instance__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cfg__instances__field_descriptors[1] =
{
  {
    "instance",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(CFGINSTANCES, n_instance),
    PROTOBUF_C_OFFSETOF(CFGINSTANCES, instance),
    &cfg__instance__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cfg__instances__field_indices_by_name[] = {
  0,   /* field[0] = instance */
};
static const ProtobufCIntRange cfg__instances__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor cfg__instances__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "CFG_INSTANCES",
  "CFGINSTANCES",
  "CFGINSTANCES",
  "",
  sizeof(CFGINSTANCES),
  1,
  cfg__instances__field_descriptors,
  cfg__instances__field_indices_by_name,
  1,  cfg__instances__number_ranges,
  (ProtobufCMessageInit) cfg__instances__init,
  NULL,NULL,NULL    /* reserved[123] */
};
