/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_config_5fname_2eproto__INCLUDED
#define PROTOBUF_C_config_5fname_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _CFGNAME CFGNAME;


/* --- enums --- */


/* --- messages --- */

struct  _CFGNAME
{
  ProtobufCMessage base;
  size_t n_fam_name;
  char **fam_name;
  size_t n_male_name;
  char **male_name;
  size_t n_female_name;
  char **female_name;
};
#define CFG__NAME__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cfg__name__descriptor) \
    , 0,NULL, 0,NULL, 0,NULL }


/* CFGNAME methods */
void   cfg__name__init
                     (CFGNAME         *message);
size_t cfg__name__get_packed_size
                     (const CFGNAME   *message);
size_t cfg__name__pack
                     (const CFGNAME   *message,
                      uint8_t             *out);
size_t cfg__name__pack_to_buffer
                     (const CFGNAME   *message,
                      ProtobufCBuffer     *buffer);
CFGNAME *
       cfg__name__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cfg__name__free_unpacked
                     (CFGNAME *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CFGNAME_Closure)
                 (const CFGNAME *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor cfg__name__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_config_5fname_2eproto__INCLUDED */
