/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "config_map_function.pb-c.h"
void   cfg__map__function__init
                     (CFGMAPFUNCTION         *message)
{
  static CFGMAPFUNCTION init_value = CFG__MAP__FUNCTION__INIT;
  *message = init_value;
}
size_t cfg__map__function__get_packed_size
                     (const CFGMAPFUNCTION *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__map__function__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cfg__map__function__pack
                     (const CFGMAPFUNCTION *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__map__function__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cfg__map__function__pack_to_buffer
                     (const CFGMAPFUNCTION *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__map__function__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CFGMAPFUNCTION *
       cfg__map__function__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CFGMAPFUNCTION *)
     protobuf_c_message_unpack (&cfg__map__function__descriptor,
                                allocator, len, data);
}
void   cfg__map__function__free_unpacked
                     (CFGMAPFUNCTION *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__map__function__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cfg__map__functions__init
                     (CFGMAPFUNCTIONS         *message)
{
  static CFGMAPFUNCTIONS init_value = CFG__MAP__FUNCTIONS__INIT;
  *message = init_value;
}
size_t cfg__map__functions__get_packed_size
                     (const CFGMAPFUNCTIONS *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__map__functions__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cfg__map__functions__pack
                     (const CFGMAPFUNCTIONS *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__map__functions__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cfg__map__functions__pack_to_buffer
                     (const CFGMAPFUNCTIONS *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__map__functions__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CFGMAPFUNCTIONS *
       cfg__map__functions__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CFGMAPFUNCTIONS *)
     protobuf_c_message_unpack (&cfg__map__functions__descriptor,
                                allocator, len, data);
}
void   cfg__map__functions__free_unpacked
                     (CFGMAPFUNCTIONS *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__map__functions__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor cfg__map__function__field_descriptors[23] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGMAPFUNCTION, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "monster1",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGMAPFUNCTION, monster1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "monster2",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGMAPFUNCTION, monster2),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "monster3",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGMAPFUNCTION, monster3),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hp",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGMAPFUNCTION, hp),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "move",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGMAPFUNCTION, move),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "drop",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(CFGMAPFUNCTION, n_drop),
    PROTOBUF_C_OFFSETOF(CFGMAPFUNCTION, drop),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bless",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGMAPFUNCTION, bless),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bless_percent",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGMAPFUNCTION, bless_percent),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "curse",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGMAPFUNCTION, curse),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "curse_percent",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGMAPFUNCTION, curse_percent),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shop",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGMAPFUNCTION, shop),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shop_percent",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGMAPFUNCTION, shop_percent),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gold",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGMAPFUNCTION, gold),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gold_percent",
    15,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGMAPFUNCTION, gold_percent),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "elite",
    16,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGMAPFUNCTION, elite),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "elite_percent",
    17,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGMAPFUNCTION, elite_percent),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "drop_delta",
    18,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGMAPFUNCTION, drop_delta),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "drop_delta_percent",
    19,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGMAPFUNCTION, drop_delta_percent),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "money_delta",
    20,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGMAPFUNCTION, money_delta),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "money_delta_percent",
    21,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGMAPFUNCTION, money_delta_percent),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exp_delta",
    22,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGMAPFUNCTION, exp_delta),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exp_delta_percent",
    23,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGMAPFUNCTION, exp_delta_percent),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cfg__map__function__field_indices_by_name[] = {
  7,   /* field[7] = bless */
  8,   /* field[8] = bless_percent */
  9,   /* field[9] = curse */
  10,   /* field[10] = curse_percent */
  6,   /* field[6] = drop */
  17,   /* field[17] = drop_delta */
  18,   /* field[18] = drop_delta_percent */
  15,   /* field[15] = elite */
  16,   /* field[16] = elite_percent */
  21,   /* field[21] = exp_delta */
  22,   /* field[22] = exp_delta_percent */
  13,   /* field[13] = gold */
  14,   /* field[14] = gold_percent */
  4,   /* field[4] = hp */
  0,   /* field[0] = id */
  19,   /* field[19] = money_delta */
  20,   /* field[20] = money_delta_percent */
  1,   /* field[1] = monster1 */
  2,   /* field[2] = monster2 */
  3,   /* field[3] = monster3 */
  5,   /* field[5] = move */
  11,   /* field[11] = shop */
  12,   /* field[12] = shop_percent */
};
static const ProtobufCIntRange cfg__map__function__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 23 }
};
const ProtobufCMessageDescriptor cfg__map__function__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "CFG_MAP_FUNCTION",
  "CFGMAPFUNCTION",
  "CFGMAPFUNCTION",
  "",
  sizeof(CFGMAPFUNCTION),
  23,
  cfg__map__function__field_descriptors,
  cfg__map__function__field_indices_by_name,
  1,  cfg__map__function__number_ranges,
  (ProtobufCMessageInit) cfg__map__function__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cfg__map__functions__field_descriptors[1] =
{
  {
    "map_function",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(CFGMAPFUNCTIONS, n_map_function),
    PROTOBUF_C_OFFSETOF(CFGMAPFUNCTIONS, map_function),
    &cfg__map__function__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cfg__map__functions__field_indices_by_name[] = {
  0,   /* field[0] = map_function */
};
static const ProtobufCIntRange cfg__map__functions__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor cfg__map__functions__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "CFG_MAP_FUNCTIONS",
  "CFGMAPFUNCTIONS",
  "CFGMAPFUNCTIONS",
  "",
  sizeof(CFGMAPFUNCTIONS),
  1,
  cfg__map__functions__field_descriptors,
  cfg__map__functions__field_indices_by_name,
  1,  cfg__map__functions__number_ranges,
  (ProtobufCMessageInit) cfg__map__functions__init,
  NULL,NULL,NULL    /* reserved[123] */
};
