/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "config_scene.pb-c.h"
void   npc_info__init
                     (NpcInfo         *message)
{
  static NpcInfo init_value = NPC_INFO__INIT;
  *message = init_value;
}
size_t npc_info__get_packed_size
                     (const NpcInfo *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &npc_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t npc_info__pack
                     (const NpcInfo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &npc_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t npc_info__pack_to_buffer
                     (const NpcInfo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &npc_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NpcInfo *
       npc_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NpcInfo *)
     protobuf_c_message_unpack (&npc_info__descriptor,
                                allocator, len, data);
}
void   npc_info__free_unpacked
                     (NpcInfo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &npc_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cfg__scene__init
                     (CFGSCENE         *message)
{
  static CFGSCENE init_value = CFG__SCENE__INIT;
  *message = init_value;
}
size_t cfg__scene__get_packed_size
                     (const CFGSCENE *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__scene__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cfg__scene__pack
                     (const CFGSCENE *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__scene__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cfg__scene__pack_to_buffer
                     (const CFGSCENE *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__scene__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CFGSCENE *
       cfg__scene__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CFGSCENE *)
     protobuf_c_message_unpack (&cfg__scene__descriptor,
                                allocator, len, data);
}
void   cfg__scene__free_unpacked
                     (CFGSCENE *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__scene__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cfg__scenes__init
                     (CFGSCENES         *message)
{
  static CFGSCENES init_value = CFG__SCENES__INIT;
  *message = init_value;
}
size_t cfg__scenes__get_packed_size
                     (const CFGSCENES *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__scenes__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cfg__scenes__pack
                     (const CFGSCENES *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__scenes__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cfg__scenes__pack_to_buffer
                     (const CFGSCENES *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__scenes__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CFGSCENES *
       cfg__scenes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CFGSCENES *)
     protobuf_c_message_unpack (&cfg__scenes__descriptor,
                                allocator, len, data);
}
void   cfg__scenes__free_unpacked
                     (CFGSCENES *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cfg__scenes__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor npc_info__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NpcInfo, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_x",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NpcInfo, pos_x),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_y",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NpcInfo, pos_y),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned npc_info__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = pos_x */
  2,   /* field[2] = pos_y */
};
static const ProtobufCIntRange npc_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor npc_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "npc_info",
  "NpcInfo",
  "NpcInfo",
  "",
  sizeof(NpcInfo),
  3,
  npc_info__field_descriptors,
  npc_info__field_indices_by_name,
  1,  npc_info__number_ranges,
  (ProtobufCMessageInit) npc_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cfg__scene__field_descriptors[9] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGSCENE, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGSCENE, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "width",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGSCENE, width),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGSCENE, height),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enter_pos_x",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGSCENE, enter_pos_x),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enter_pos_y",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGSCENE, enter_pos_y),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "valid_height",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CFGSCENE, valid_height),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "npc_info",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(CFGSCENE, n_npc_info),
    PROTOBUF_C_OFFSETOF(CFGSCENE, npc_info),
    &npc_info__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instance_id",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(CFGSCENE, n_instance_id),
    PROTOBUF_C_OFFSETOF(CFGSCENE, instance_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cfg__scene__field_indices_by_name[] = {
  4,   /* field[4] = enter_pos_x */
  5,   /* field[5] = enter_pos_y */
  3,   /* field[3] = height */
  0,   /* field[0] = id */
  8,   /* field[8] = instance_id */
  1,   /* field[1] = name */
  7,   /* field[7] = npc_info */
  6,   /* field[6] = valid_height */
  2,   /* field[2] = width */
};
static const ProtobufCIntRange cfg__scene__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor cfg__scene__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "CFG_SCENE",
  "CFGSCENE",
  "CFGSCENE",
  "",
  sizeof(CFGSCENE),
  9,
  cfg__scene__field_descriptors,
  cfg__scene__field_indices_by_name,
  1,  cfg__scene__number_ranges,
  (ProtobufCMessageInit) cfg__scene__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cfg__scenes__field_descriptors[1] =
{
  {
    "scene",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(CFGSCENES, n_scene),
    PROTOBUF_C_OFFSETOF(CFGSCENES, scene),
    &cfg__scene__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cfg__scenes__field_indices_by_name[] = {
  0,   /* field[0] = scene */
};
static const ProtobufCIntRange cfg__scenes__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor cfg__scenes__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "CFG_SCENES",
  "CFGSCENES",
  "CFGSCENES",
  "",
  sizeof(CFGSCENES),
  1,
  cfg__scenes__field_descriptors,
  cfg__scenes__field_indices_by_name,
  1,  cfg__scenes__number_ranges,
  (ProtobufCMessageInit) cfg__scenes__init,
  NULL,NULL,NULL    /* reserved[123] */
};
