/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_config_5fplayer_2eproto__INCLUDED
#define PROTOBUF_C_config_5fplayer_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _CFGPLAYER CFGPLAYER;
typedef struct _CFGPLAYERS CFGPLAYERS;


/* --- enums --- */


/* --- messages --- */

struct  _CFGPLAYER
{
  ProtobufCMessage base;
  int32_t prof;
  int32_t level;
  int32_t sex;
  int32_t exp;
  int32_t attribute;
};
#define CFG__PLAYER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cfg__player__descriptor) \
    , 0, 0, 0, 0, 0 }


struct  _CFGPLAYERS
{
  ProtobufCMessage base;
  size_t n_player;
  CFGPLAYER **player;
};
#define CFG__PLAYERS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cfg__players__descriptor) \
    , 0,NULL }


/* CFGPLAYER methods */
void   cfg__player__init
                     (CFGPLAYER         *message);
size_t cfg__player__get_packed_size
                     (const CFGPLAYER   *message);
size_t cfg__player__pack
                     (const CFGPLAYER   *message,
                      uint8_t             *out);
size_t cfg__player__pack_to_buffer
                     (const CFGPLAYER   *message,
                      ProtobufCBuffer     *buffer);
CFGPLAYER *
       cfg__player__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cfg__player__free_unpacked
                     (CFGPLAYER *message,
                      ProtobufCAllocator *allocator);
/* CFGPLAYERS methods */
void   cfg__players__init
                     (CFGPLAYERS         *message);
size_t cfg__players__get_packed_size
                     (const CFGPLAYERS   *message);
size_t cfg__players__pack
                     (const CFGPLAYERS   *message,
                      uint8_t             *out);
size_t cfg__players__pack_to_buffer
                     (const CFGPLAYERS   *message,
                      ProtobufCBuffer     *buffer);
CFGPLAYERS *
       cfg__players__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cfg__players__free_unpacked
                     (CFGPLAYERS *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CFGPLAYER_Closure)
                 (const CFGPLAYER *message,
                  void *closure_data);
typedef void (*CFGPLAYERS_Closure)
                 (const CFGPLAYERS *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor cfg__player__descriptor;
extern const ProtobufCMessageDescriptor cfg__players__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_config_5fplayer_2eproto__INCLUDED */
