/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "db_bag.pb-c.h"
void   db_thing__init
                     (DbThing         *message)
{
  static DbThing init_value = DB_THING__INIT;
  *message = init_value;
}
size_t db_thing__get_packed_size
                     (const DbThing *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_thing__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t db_thing__pack
                     (const DbThing *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_thing__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t db_thing__pack_to_buffer
                     (const DbThing *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_thing__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbThing *
       db_thing__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbThing *)
     protobuf_c_message_unpack (&db_thing__descriptor,
                                allocator, len, data);
}
void   db_thing__free_unpacked
                     (DbThing *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_thing__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   db_bag__init
                     (DbBag         *message)
{
  static DbBag init_value = DB_BAG__INIT;
  *message = init_value;
}
size_t db_bag__get_packed_size
                     (const DbBag *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_bag__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t db_bag__pack
                     (const DbBag *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_bag__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t db_bag__pack_to_buffer
                     (const DbBag *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_bag__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbBag *
       db_bag__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbBag *)
     protobuf_c_message_unpack (&db_bag__descriptor,
                                allocator, len, data);
}
void   db_bag__free_unpacked
                     (DbBag *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_bag__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor db_thing__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbThing, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbThing, num),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbThing, pos),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned db_thing__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = num */
  2,   /* field[2] = pos */
};
static const ProtobufCIntRange db_thing__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor db_thing__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "db_thing",
  "DbThing",
  "DbThing",
  "",
  sizeof(DbThing),
  3,
  db_thing__field_descriptors,
  db_thing__field_indices_by_name,
  1,  db_thing__number_ranges,
  (ProtobufCMessageInit) db_thing__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor db_bag__field_descriptors[2] =
{
  {
    "max_num",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbBag, max_num),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "things",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(DbBag, n_things),
    PROTOBUF_C_OFFSETOF(DbBag, things),
    &db_thing__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned db_bag__field_indices_by_name[] = {
  0,   /* field[0] = max_num */
  1,   /* field[1] = things */
};
static const ProtobufCIntRange db_bag__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor db_bag__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "db_bag",
  "DbBag",
  "DbBag",
  "",
  sizeof(DbBag),
  2,
  db_bag__field_descriptors,
  db_bag__field_indices_by_name,
  1,  db_bag__number_ranges,
  (ProtobufCMessageInit) db_bag__init,
  NULL,NULL,NULL    /* reserved[123] */
};
