/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "db_role_info.pb-c.h"
void   db_thing__init
                     (DbThing         *message)
{
  static DbThing init_value = DB_THING__INIT;
  *message = init_value;
}
size_t db_thing__get_packed_size
                     (const DbThing *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_thing__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t db_thing__pack
                     (const DbThing *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_thing__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t db_thing__pack_to_buffer
                     (const DbThing *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_thing__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbThing *
       db_thing__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbThing *)
     protobuf_c_message_unpack (&db_thing__descriptor,
                                allocator, len, data);
}
void   db_thing__free_unpacked
                     (DbThing *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_thing__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   db_bag__init
                     (DbBag         *message)
{
  static DbBag init_value = DB_BAG__INIT;
  *message = init_value;
}
size_t db_bag__get_packed_size
                     (const DbBag *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_bag__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t db_bag__pack
                     (const DbBag *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_bag__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t db_bag__pack_to_buffer
                     (const DbBag *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_bag__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbBag *
       db_bag__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbBag *)
     protobuf_c_message_unpack (&db_bag__descriptor,
                                allocator, len, data);
}
void   db_bag__free_unpacked
                     (DbBag *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_bag__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   db_quest_progress__init
                     (DbQuestProgress         *message)
{
  static DbQuestProgress init_value = DB_QUEST_PROGRESS__INIT;
  *message = init_value;
}
size_t db_quest_progress__get_packed_size
                     (const DbQuestProgress *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_quest_progress__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t db_quest_progress__pack
                     (const DbQuestProgress *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_quest_progress__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t db_quest_progress__pack_to_buffer
                     (const DbQuestProgress *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_quest_progress__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbQuestProgress *
       db_quest_progress__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbQuestProgress *)
     protobuf_c_message_unpack (&db_quest_progress__descriptor,
                                allocator, len, data);
}
void   db_quest_progress__free_unpacked
                     (DbQuestProgress *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_quest_progress__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   db_quest_progress_list__init
                     (DbQuestProgressList         *message)
{
  static DbQuestProgressList init_value = DB_QUEST_PROGRESS_LIST__INIT;
  *message = init_value;
}
size_t db_quest_progress_list__get_packed_size
                     (const DbQuestProgressList *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_quest_progress_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t db_quest_progress_list__pack
                     (const DbQuestProgressList *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_quest_progress_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t db_quest_progress_list__pack_to_buffer
                     (const DbQuestProgressList *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_quest_progress_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbQuestProgressList *
       db_quest_progress_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbQuestProgressList *)
     protobuf_c_message_unpack (&db_quest_progress_list__descriptor,
                                allocator, len, data);
}
void   db_quest_progress_list__free_unpacked
                     (DbQuestProgressList *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_quest_progress_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   db_one_role__init
                     (DbOneRole         *message)
{
  static DbOneRole init_value = DB_ONE_ROLE__INIT;
  *message = init_value;
}
size_t db_one_role__get_packed_size
                     (const DbOneRole *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_one_role__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t db_one_role__pack
                     (const DbOneRole *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_one_role__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t db_one_role__pack_to_buffer
                     (const DbOneRole *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_one_role__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbOneRole *
       db_one_role__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbOneRole *)
     protobuf_c_message_unpack (&db_one_role__descriptor,
                                allocator, len, data);
}
void   db_one_role__free_unpacked
                     (DbOneRole *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_one_role__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   db_shortcut__init
                     (DbShortcut         *message)
{
  static DbShortcut init_value = DB_SHORTCUT__INIT;
  *message = init_value;
}
size_t db_shortcut__get_packed_size
                     (const DbShortcut *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_shortcut__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t db_shortcut__pack
                     (const DbShortcut *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_shortcut__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t db_shortcut__pack_to_buffer
                     (const DbShortcut *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_shortcut__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbShortcut *
       db_shortcut__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbShortcut *)
     protobuf_c_message_unpack (&db_shortcut__descriptor,
                                allocator, len, data);
}
void   db_shortcut__free_unpacked
                     (DbShortcut *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_shortcut__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   db_friend__init
                     (DbFriend         *message)
{
  static DbFriend init_value = DB_FRIEND__INIT;
  *message = init_value;
}
size_t db_friend__get_packed_size
                     (const DbFriend *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_friend__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t db_friend__pack
                     (const DbFriend *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_friend__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t db_friend__pack_to_buffer
                     (const DbFriend *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_friend__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbFriend *
       db_friend__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbFriend *)
     protobuf_c_message_unpack (&db_friend__descriptor,
                                allocator, len, data);
}
void   db_friend__free_unpacked
                     (DbFriend *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_friend__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   db_blob_role_info__init
                     (DbBlobRoleInfo         *message)
{
  static DbBlobRoleInfo init_value = DB_BLOB_ROLE_INFO__INIT;
  *message = init_value;
}
size_t db_blob_role_info__get_packed_size
                     (const DbBlobRoleInfo *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_blob_role_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t db_blob_role_info__pack
                     (const DbBlobRoleInfo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_blob_role_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t db_blob_role_info__pack_to_buffer
                     (const DbBlobRoleInfo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_blob_role_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DbBlobRoleInfo *
       db_blob_role_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DbBlobRoleInfo *)
     protobuf_c_message_unpack (&db_blob_role_info__descriptor,
                                allocator, len, data);
}
void   db_blob_role_info__free_unpacked
                     (DbBlobRoleInfo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &db_blob_role_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor db_thing__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbThing, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbThing, num),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbThing, pos),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned db_thing__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = num */
  2,   /* field[2] = pos */
};
static const ProtobufCIntRange db_thing__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor db_thing__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "db_thing",
  "DbThing",
  "DbThing",
  "",
  sizeof(DbThing),
  3,
  db_thing__field_descriptors,
  db_thing__field_indices_by_name,
  1,  db_thing__number_ranges,
  (ProtobufCMessageInit) db_thing__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor db_bag__field_descriptors[2] =
{
  {
    "max_num",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbBag, max_num),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "things",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(DbBag, n_things),
    PROTOBUF_C_OFFSETOF(DbBag, things),
    &db_thing__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned db_bag__field_indices_by_name[] = {
  0,   /* field[0] = max_num */
  1,   /* field[1] = things */
};
static const ProtobufCIntRange db_bag__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor db_bag__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "db_bag",
  "DbBag",
  "DbBag",
  "",
  sizeof(DbBag),
  2,
  db_bag__field_descriptors,
  db_bag__field_indices_by_name,
  1,  db_bag__number_ranges,
  (ProtobufCMessageInit) db_bag__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor db_quest_progress__field_descriptors[10] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbQuestProgress, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbQuestProgress, state),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accept_time",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbQuestProgress, accept_time),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cycle_num",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbQuestProgress, cycle_num),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kill_npc1_num",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbQuestProgress, kill_npc1_num),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kill_npc2_num",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbQuestProgress, kill_npc2_num),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kill_npc3_num",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbQuestProgress, kill_npc3_num),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "collect_item1_num",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbQuestProgress, collect_item1_num),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "collect_item2_num",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbQuestProgress, collect_item2_num),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "collect_item3_num",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbQuestProgress, collect_item3_num),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned db_quest_progress__field_indices_by_name[] = {
  2,   /* field[2] = accept_time */
  7,   /* field[7] = collect_item1_num */
  8,   /* field[8] = collect_item2_num */
  9,   /* field[9] = collect_item3_num */
  3,   /* field[3] = cycle_num */
  0,   /* field[0] = id */
  4,   /* field[4] = kill_npc1_num */
  5,   /* field[5] = kill_npc2_num */
  6,   /* field[6] = kill_npc3_num */
  1,   /* field[1] = state */
};
static const ProtobufCIntRange db_quest_progress__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor db_quest_progress__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "db_quest_progress",
  "DbQuestProgress",
  "DbQuestProgress",
  "",
  sizeof(DbQuestProgress),
  10,
  db_quest_progress__field_descriptors,
  db_quest_progress__field_indices_by_name,
  1,  db_quest_progress__number_ranges,
  (ProtobufCMessageInit) db_quest_progress__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor db_quest_progress_list__field_descriptors[3] =
{
  {
    "quest",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(DbQuestProgressList, n_quest),
    PROTOBUF_C_OFFSETOF(DbQuestProgressList, quest),
    &db_quest_progress__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "main_quest_index",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbQuestProgressList, main_quest_index),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "all_finished_slave_quest",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(DbQuestProgressList, n_all_finished_slave_quest),
    PROTOBUF_C_OFFSETOF(DbQuestProgressList, all_finished_slave_quest),
    NULL,
    NULL,
    1,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned db_quest_progress_list__field_indices_by_name[] = {
  2,   /* field[2] = all_finished_slave_quest */
  1,   /* field[1] = main_quest_index */
  0,   /* field[0] = quest */
};
static const ProtobufCIntRange db_quest_progress_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor db_quest_progress_list__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "db_quest_progress_list",
  "DbQuestProgressList",
  "DbQuestProgressList",
  "",
  sizeof(DbQuestProgressList),
  3,
  db_quest_progress_list__field_descriptors,
  db_quest_progress_list__field_indices_by_name,
  1,  db_quest_progress_list__number_ranges,
  (ProtobufCMessageInit) db_quest_progress_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor db_one_role__field_descriptors[7] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbOneRole, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "level",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbOneRole, level),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prof",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbOneRole, prof),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exp",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbOneRole, exp),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "equip",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(DbOneRole, n_equip),
    PROTOBUF_C_OFFSETOF(DbOneRole, equip),
    NULL,
    NULL,
    1,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "skill",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(DbOneRole, n_skill),
    PROTOBUF_C_OFFSETOF(DbOneRole, skill),
    NULL,
    NULL,
    1,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "active_skill",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(DbOneRole, n_active_skill),
    PROTOBUF_C_OFFSETOF(DbOneRole, active_skill),
    NULL,
    NULL,
    1,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned db_one_role__field_indices_by_name[] = {
  6,   /* field[6] = active_skill */
  4,   /* field[4] = equip */
  3,   /* field[3] = exp */
  1,   /* field[1] = level */
  0,   /* field[0] = name */
  2,   /* field[2] = prof */
  5,   /* field[5] = skill */
};
static const ProtobufCIntRange db_one_role__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor db_one_role__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "db_one_role",
  "DbOneRole",
  "DbOneRole",
  "",
  sizeof(DbOneRole),
  7,
  db_one_role__field_descriptors,
  db_one_role__field_indices_by_name,
  1,  db_one_role__number_ranges,
  (ProtobufCMessageInit) db_one_role__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor db_shortcut__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbShortcut, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbShortcut, pos),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned db_shortcut__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = pos */
};
static const ProtobufCIntRange db_shortcut__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor db_shortcut__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "db_shortcut",
  "DbShortcut",
  "DbShortcut",
  "",
  sizeof(DbShortcut),
  2,
  db_shortcut__field_descriptors,
  db_shortcut__field_indices_by_name,
  1,  db_shortcut__number_ranges,
  (ProtobufCMessageInit) db_shortcut__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor db_friend__field_descriptors[2] =
{
  {
    "friend",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(DbFriend, n_friend_),
    PROTOBUF_C_OFFSETOF(DbFriend, friend_),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blacklist",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(DbFriend, n_blacklist),
    PROTOBUF_C_OFFSETOF(DbFriend, blacklist),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned db_friend__field_indices_by_name[] = {
  1,   /* field[1] = blacklist */
  0,   /* field[0] = friend */
};
static const ProtobufCIntRange db_friend__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor db_friend__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "db_friend",
  "DbFriend",
  "DbFriend",
  "",
  sizeof(DbFriend),
  2,
  db_friend__field_descriptors,
  db_friend__field_indices_by_name,
  1,  db_friend__number_ranges,
  (ProtobufCMessageInit) db_friend__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor db_blob_role_info__field_descriptors[5] =
{
  {
    "bag",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbBlobRoleInfo, bag),
    &db_bag__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quest",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbBlobRoleInfo, quest),
    &db_quest_progress_list__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "one_role",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(DbBlobRoleInfo, n_one_role),
    PROTOBUF_C_OFFSETOF(DbBlobRoleInfo, one_role),
    &db_one_role__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shortcut",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(DbBlobRoleInfo, n_shortcut),
    PROTOBUF_C_OFFSETOF(DbBlobRoleInfo, shortcut),
    &db_shortcut__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "game_friend",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DbBlobRoleInfo, game_friend),
    &db_friend__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned db_blob_role_info__field_indices_by_name[] = {
  0,   /* field[0] = bag */
  4,   /* field[4] = game_friend */
  2,   /* field[2] = one_role */
  1,   /* field[1] = quest */
  3,   /* field[3] = shortcut */
};
static const ProtobufCIntRange db_blob_role_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor db_blob_role_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "db_blob_role_info",
  "DbBlobRoleInfo",
  "DbBlobRoleInfo",
  "",
  sizeof(DbBlobRoleInfo),
  5,
  db_blob_role_info__field_descriptors,
  db_blob_role_info__field_indices_by_name,
  1,  db_blob_role_info__number_ranges,
  (ProtobufCMessageInit) db_blob_role_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
