/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "scene.pb-c.h"
void   test_msg__init
                     (TestMsg         *message)
{
  static TestMsg init_value = TEST_MSG__INIT;
  *message = init_value;
}
size_t test_msg__get_packed_size
                     (const TestMsg *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &test_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t test_msg__pack
                     (const TestMsg *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &test_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t test_msg__pack_to_buffer
                     (const TestMsg *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &test_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TestMsg *
       test_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TestMsg *)
     protobuf_c_message_unpack (&test_msg__descriptor,
                                allocator, len, data);
}
void   test_msg__free_unpacked
                     (TestMsg *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &test_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scene__init
                     (SCENE         *message)
{
  static SCENE init_value = SCENE__INIT;
  *message = init_value;
}
size_t scene__get_packed_size
                     (const SCENE *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scene__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scene__pack
                     (const SCENE *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scene__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scene__pack_to_buffer
                     (const SCENE *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scene__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SCENE *
       scene__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SCENE *)
     protobuf_c_message_unpack (&scene__descriptor,
                                allocator, len, data);
}
void   scene__free_unpacked
                     (SCENE *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scene__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scenes__init
                     (SCENES         *message)
{
  static SCENES init_value = SCENES__INIT;
  *message = init_value;
}
size_t scenes__get_packed_size
                     (const SCENES *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scenes__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scenes__pack
                     (const SCENES *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scenes__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scenes__pack_to_buffer
                     (const SCENES *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scenes__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SCENES *
       scenes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SCENES *)
     protobuf_c_message_unpack (&scenes__descriptor,
                                allocator, len, data);
}
void   scenes__free_unpacked
                     (SCENES *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &scenes__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor test_msg__field_descriptors[2] =
{
  {
    "pos_x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TestMsg, pos_x),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TestMsg, pos_y),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned test_msg__field_indices_by_name[] = {
  0,   /* field[0] = pos_x */
  1,   /* field[1] = pos_y */
};
static const ProtobufCIntRange test_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor test_msg__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "test_msg",
  "TestMsg",
  "TestMsg",
  "",
  sizeof(TestMsg),
  2,
  test_msg__field_descriptors,
  test_msg__field_indices_by_name,
  1,  test_msg__number_ranges,
  (ProtobufCMessageInit) test_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scene__field_descriptors[6] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SCENE, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SCENE, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "width",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SCENE, width),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SCENE, height),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "valid_height",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SCENE, valid_height),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(SCENE, n_msg),
    PROTOBUF_C_OFFSETOF(SCENE, msg),
    &test_msg__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scene__field_indices_by_name[] = {
  3,   /* field[3] = height */
  0,   /* field[0] = id */
  5,   /* field[5] = msg */
  1,   /* field[1] = name */
  4,   /* field[4] = valid_height */
  2,   /* field[2] = width */
};
static const ProtobufCIntRange scene__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor scene__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "SCENE",
  "SCENE",
  "SCENE",
  "",
  sizeof(SCENE),
  6,
  scene__field_descriptors,
  scene__field_indices_by_name,
  1,  scene__number_ranges,
  (ProtobufCMessageInit) scene__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scenes__field_descriptors[1] =
{
  {
    "scene",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(SCENES, n_scene),
    PROTOBUF_C_OFFSETOF(SCENES, scene),
    &scene__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scenes__field_indices_by_name[] = {
  0,   /* field[0] = scene */
};
static const ProtobufCIntRange scenes__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor scenes__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "SCENES",
  "SCENES",
  "SCENES",
  "",
  sizeof(SCENES),
  1,
  scenes__field_descriptors,
  scenes__field_indices_by_name,
  1,  scenes__number_ranges,
  (ProtobufCMessageInit) scenes__init,
  NULL,NULL,NULL    /* reserved[123] */
};
