/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "transport.pb-c.h"
void   transport__init
                     (TRANSPORT         *message)
{
  static TRANSPORT init_value = TRANSPORT__INIT;
  *message = init_value;
}
size_t transport__get_packed_size
                     (const TRANSPORT *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transport__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t transport__pack
                     (const TRANSPORT *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transport__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t transport__pack_to_buffer
                     (const TRANSPORT *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transport__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TRANSPORT *
       transport__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TRANSPORT *)
     protobuf_c_message_unpack (&transport__descriptor,
                                allocator, len, data);
}
void   transport__free_unpacked
                     (TRANSPORT *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transport__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   transports__init
                     (TRANSPORTS         *message)
{
  static TRANSPORTS init_value = TRANSPORTS__INIT;
  *message = init_value;
}
size_t transports__get_packed_size
                     (const TRANSPORTS *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transports__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t transports__pack
                     (const TRANSPORTS *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transports__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t transports__pack_to_buffer
                     (const TRANSPORTS *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transports__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TRANSPORTS *
       transports__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TRANSPORTS *)
     protobuf_c_message_unpack (&transports__descriptor,
                                allocator, len, data);
}
void   transports__free_unpacked
                     (TRANSPORTS *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &transports__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor transport__field_descriptors[8] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TRANSPORT, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TRANSPORT, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "src_scene_id",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TRANSPORT, src_scene_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "src_pos_x",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TRANSPORT, src_pos_x),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "src_pos_y",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TRANSPORT, src_pos_y),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dst_scene_id",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TRANSPORT, dst_scene_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dst_pos_x",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TRANSPORT, dst_pos_x),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dst_pos_y",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TRANSPORT, dst_pos_y),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned transport__field_indices_by_name[] = {
  6,   /* field[6] = dst_pos_x */
  7,   /* field[7] = dst_pos_y */
  5,   /* field[5] = dst_scene_id */
  0,   /* field[0] = id */
  1,   /* field[1] = name */
  3,   /* field[3] = src_pos_x */
  4,   /* field[4] = src_pos_y */
  2,   /* field[2] = src_scene_id */
};
static const ProtobufCIntRange transport__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor transport__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "TRANSPORT",
  "TRANSPORT",
  "TRANSPORT",
  "",
  sizeof(TRANSPORT),
  8,
  transport__field_descriptors,
  transport__field_indices_by_name,
  1,  transport__number_ranges,
  (ProtobufCMessageInit) transport__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor transports__field_descriptors[1] =
{
  {
    "transport",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(TRANSPORTS, n_transport),
    PROTOBUF_C_OFFSETOF(TRANSPORTS, transport),
    &transport__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned transports__field_indices_by_name[] = {
  0,   /* field[0] = transport */
};
static const ProtobufCIntRange transports__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor transports__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "TRANSPORTS",
  "TRANSPORTS",
  "TRANSPORTS",
  "",
  sizeof(TRANSPORTS),
  1,
  transports__field_descriptors,
  transports__field_indices_by_name,
  1,  transports__number_ranges,
  (ProtobufCMessageInit) transports__init,
  NULL,NULL,NULL    /* reserved[123] */
};
