all:
	make -C tools/xls
	make -C lib
	make -C conn_srv
	make -C game_srv
	make -C db_srv

clean:
	make -C tools/xls clean
	make -C lib clean
	make -C conn_srv clean
	make -C game_srv clean
	make -C db_srv clean

